### ISSUE TITLE
Visualization?

### ISSUE THREAD

**Issue by Benfeitas** [mdozmorov/HiC_data#1]
Hi Mihail, I'm wondering what is your experience with visualization tools that integrate HiC, chipseq, etc.? Would greatly appreciate any advice!

**Comment by mdozmorov** [comment]
Many do it on an ad hoc basis, including us. We used Juicer, HiCseg. Here is the collection of some tools that were specifically designed for visualization and integration of other data, https://github.com/mdozmorov/HiC_tools#visualization
